/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["hello_v1_hello_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister tous les threads
         * @description Route pour récupérer tous les threads.
         */
        get: operations["get_all_threads_v1_threads__get"];
        put?: never;
        /**
         * Créer un nouveau thread
         * @description Route pour créer un thread.
         */
        post: operations["create_thread_v1_threads__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/actual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtenir le thread actuellement connecté
         * @description Route pour obtenir le thread sur lequel le client est connecté actuellement, tu peux utiliser çà pour faire l'auth,
         *     Genre Firstly au chargement de l'app, tu fais une requete sur cette route pour savoir si le client est déjà connecté
         *      à un thread ou pas, si c'est le cas tu lui redirige vers la page du thread pour voir ou ajouter un message, si
         *      c'est pas le cas tu rediriges vers la route pour voir les threads et choisir celui auquel on veut se bind
         */
        get: operations["get_connected_thread_info_v1_threads_actual_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/actual/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtenir les membres du thread actuellement connecté
         * @description Route pour obtenir les membres du thread sur lequel le client est connecté.
         *
         *     Utilise le token d'authentification pour identifier le thread et retourne
         *     la liste de tous ses membres actifs, tout est automatique comme une **Cybertrkuck**
         */
        get: operations["get_connected_thread_members_v1_threads_actual_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupérer un thread par son slug
         * @description Route pour récupérer un thread par son slug.
         */
        get: operations["get_thread_by_slug_v1_threads_slug__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Se connecter à un thread
         * @description Route pour se connecter à un thread par son ID.
         */
        post: operations["connect_to_a_thread_v1_threads__thread_id__auth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupérer un thread par son ID
         * @description Route pour récupérer un thread par son ID.
         */
        get: operations["get_thread_by_id_v1_threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ajouter un message au thread connecté
         * @description Route pour ajouter un message à un thread auquel on est connecté. Le thread est déterminé par le token d'authentification fourni dans l'en-tête de la requête.
         *     **La route retourne un 429 en cas de RateLimiting**
         */
        post: operations["create_message_v1_messages__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/thread/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister TOUS les messages du thread auquel on est connecté (déprécié)
         * @deprecated
         * @description Route pour récupérer TOUS les messages du thread auquel on est actuellement connecté.
         *
         *     **Cette route est dépréciée.** Utilisez plutôt GET /messages/thread/paginated/ pour une pagination efficace.
         */
        get: operations["get_thread_messages_v1_messages_thread__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/thread/paginated/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les messages du thread avec pagination par curseur
         * @description Route pour récupérer les messages du thread actuel avec pagination par curseur.
         *
         *     Cette route implémente une pagination par curseur (cursor-based pagination) optimisée pour :
         *     - Une meilleure performance avec de grands volumes de messages
         *     - Une navigation fluide entre les pages
         *     - Un cache efficace des résultats paginés
         *     - Une expérience utilisateur optimale
         *
         *     **Paramètres :**
         *     - `limit` : Nombre de messages par page (1-100, par défaut 20)
         *     - `cursor` : Curseur pour la page suivante ou précédente (encodé en base64).
         *                  Si None, récupère la première page (messages les plus récents)
         *
         *     **Réponse :**
         *     - `messages` : Liste des messages de la page actuelle
         *     - `has_next_page` : True s'il y a une page suivante
         *     - `next_cursor` : Curseur pour la page suivante (à utiliser avec le même limit)
         *     - `has_previous_page` : True s'il y a une page précédente
         *     - `previous_cursor` : Curseur pour la page précédente
         *
         *     **Exemple d'utilisation :**
         *     1. Première requête : GET /messages/thread/paginated/?limit=20
         *        -> Retourne les 20 messages les plus récents avec next_cursor si applicable
         *
         *     2. Page suivante : GET /messages/thread/paginated/?limit=20&cursor=<next_cursor>
         *        -> Retourne les 20 messages suivants (plus anciens)
         *
         *     3. Page précédente : GET /messages/thread/paginated/?limit=20&cursor=<previous_cursor>
         *        -> Retourne les 20 messages précédents (plus récents)
         */
        get: operations["get_thread_messages_paginated_v1_messages_thread_paginated__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupérer un message par son ID
         * @description Route pour récupérer un message par son ID.
         */
        get: operations["get_message_by_id_v1_messages__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppError
         * @description Modèle de données pour représenter une erreur métier.
         */
        AppError: {
            /**
             * Type d'erreur métier
             * @description Le type d'erreur métier qui s'est produite, utilisé pour catégoriser les erreurs et faciliter la gestion des erreurs dans coté frontend
             */
            error_type: components["schemas"]["AppErrorType"];
            /**
             * Champ des erreurs affichable directement à l'utilisateur (Texte User friendly)
             * @description Présent seulement si la requete à échouée ou si quelque chose s'est mal passé durant le traitement
             */
            error_message: string;
        };
        /**
         * AppErrorType
         * @enum {string}
         */
        AppErrorType: "LOCKED_CONTENT" | "NOT_FOUND" | "UNKNOWN_ERROR" | "BAD_REQUEST" | "UNAUTHORIZED" | "RATE_LIMIT_EXCEEDED";
        /** AuthErrorMessage */
        AuthErrorMessage: {
            /**
             * Detail
             * @description Message d'erreur en cas de probleme d'authentification ou d'autorisation
             */
            detail: string;
        };
        /**
         * CreateMessage
         * @description Schéma pour la création d'un message.
         */
        CreateMessage: {
            /**
             * Content
             * @description Contenu du message
             */
            content: string;
            /**
             * Mentionned Member Ids
             * @description Liste des IDs des membres mentionnés dans le message
             */
            mentionned_member_ids?: string[] | null;
        };
        /**
         * CreateThread
         * @description Schéma pour la création d'un thread.
         */
        CreateThread: {
            /**
             * Name
             * @description Nom du thread
             */
            name: string;
            /**
             * Slug
             * @description Slug unique du thread
             */
            slug: string;
            /**
             * Description
             * @description Description du thread
             */
            description?: string | null;
            /**
             * Wa Group Jid
             * @description ID de groupe WhatsApp
             */
            wa_group_jid: string;
            /**
             * Wa Group Name
             * @description Nom du groupe WhatsApp
             */
            wa_group_name?: string | null;
            /**
             * Password
             * @description Mot de passe optionnel du thread
             */
            password?: string | null;
        };
        /**
         * GlobalStringResponse
         * @description Réponse contennant uniquement un message de type string, utiliser pour les endpoints qui ne retournent
         *     pas de données spécifiques, mais juste un message de succès
         */
        GlobalStringResponse: {
            /** Champ pour véreifier si la reequete à réussi, True si la requete a reussi, False sinon */
            success: boolean;
            /** Champ pour véreifier le code de status HTTP de la réponse, 200 pour les succès, 400 pour les erreurs client, 500 pour les erreurs serveur, etc. */
            status_code: number;
            /**
             * Champ de résultat
             * @description Présent seulement si la requet à réussi
             */
            result?: components["schemas"]["StringMessage"] | null;
            /**
             * Champ des erreurs
             * @description Présent seulement si la requete à échouée ou si quelque chose s'est mal passé durant le traitement
             */
            error?: components["schemas"]["AppError"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InternalServerErrorSchema
         * @description Schéma de réponse pour les erreurs internes du serveur (500 Internal Server Error)
         */
        InternalServerErrorSchema: {
            /**
             * Success
             * @default false
             */
            success: boolean;
            /**
             * Status Code
             * @default 500
             */
            status_code: number;
            /**
             * Champ de résultat
             * @description Présent seulement si la requet à réussi
             */
            result?: null;
            /**
             * Champ des erreurs
             * @description Présent seulement si la requete à échouée ou si quelque chose s'est mal passé durant le traitement
             */
            error?: components["schemas"]["AppError"] | null;
        };
        /**
         * ListMembersInfos
         * @description Schéma enveloppe pour une liste de membres.
         */
        ListMembersInfos: {
            /** Champ pour véreifier si la reequete à réussi, True si la requete a reussi, False sinon */
            success: boolean;
            /** Champ pour véreifier le code de status HTTP de la réponse, 200 pour les succès, 400 pour les erreurs client, 500 pour les erreurs serveur, etc. */
            status_code: number;
            /**
             * Champ de résultat
             * @description Présent seulement si la requet à réussi
             */
            result?: components["schemas"]["ReadMember"][] | null;
            /**
             * Champ des erreurs
             * @description Présent seulement si la requete à échouée ou si quelque chose s'est mal passé durant le traitement
             */
            error?: components["schemas"]["AppError"] | null;
        };
        /**
         * ListMessagesInfos
         * @description Schéma enveloppe pour une liste de messages.
         */
        ListMessagesInfos: {
            /** Champ pour véreifier si la reequete à réussi, True si la requete a reussi, False sinon */
            success: boolean;
            /** Champ pour véreifier le code de status HTTP de la réponse, 200 pour les succès, 400 pour les erreurs client, 500 pour les erreurs serveur, etc. */
            status_code: number;
            /**
             * Champ de résultat
             * @description Présent seulement si la requet à réussi
             */
            result?: components["schemas"]["ReadMessage"][] | null;
            /**
             * Champ des erreurs
             * @description Présent seulement si la requete à échouée ou si quelque chose s'est mal passé durant le traitement
             */
            error?: components["schemas"]["AppError"] | null;
        };
        /**
         * ListThreadsInfos
         * @description Schéma enveloppe pour une liste de threads.
         */
        ListThreadsInfos: {
            /** Champ pour véreifier si la reequete à réussi, True si la requete a reussi, False sinon */
            success: boolean;
            /** Champ pour véreifier le code de status HTTP de la réponse, 200 pour les succès, 400 pour les erreurs client, 500 pour les erreurs serveur, etc. */
            status_code: number;
            /**
             * Champ de résultat
             * @description Présent seulement si la requet à réussi
             */
            result?: components["schemas"]["ReadThreadWithUserConnectionInfo"][] | null;
            /**
             * Champ des erreurs
             * @description Présent seulement si la requete à échouée ou si quelque chose s'est mal passé durant le traitement
             */
            error?: components["schemas"]["AppError"] | null;
        };
        /**
         * MessageInfos
         * @description Schéma enveloppe pour un message unique.
         */
        MessageInfos: {
            /** Champ pour véreifier si la reequete à réussi, True si la requete a reussi, False sinon */
            success: boolean;
            /** Champ pour véreifier le code de status HTTP de la réponse, 200 pour les succès, 400 pour les erreurs client, 500 pour les erreurs serveur, etc. */
            status_code: number;
            /**
             * Champ de résultat
             * @description Présent seulement si la requet à réussi
             */
            result?: components["schemas"]["ReadMessage"] | null;
            /**
             * Champ des erreurs
             * @description Présent seulement si la requete à échouée ou si quelque chose s'est mal passé durant le traitement
             */
            error?: components["schemas"]["AppError"] | null;
        };
        /**
         * PaginatedMessagesInfos
         * @description Schéma enveloppe pour une réponse paginée de messages.
         */
        PaginatedMessagesInfos: {
            /** Champ pour véreifier si la reequete à réussi, True si la requete a reussi, False sinon */
            success: boolean;
            /** Champ pour véreifier le code de status HTTP de la réponse, 200 pour les succès, 400 pour les erreurs client, 500 pour les erreurs serveur, etc. */
            status_code: number;
            /**
             * Champ de résultat
             * @description Présent seulement si la requet à réussi
             */
            result?: components["schemas"]["PaginatedMessagesResponse"] | null;
            /**
             * Champ des erreurs
             * @description Présent seulement si la requete à échouée ou si quelque chose s'est mal passé durant le traitement
             */
            error?: components["schemas"]["AppError"] | null;
        };
        /**
         * PaginatedMessagesResponse
         * @description Schéma pour la réponse paginée avec curseur.
         */
        PaginatedMessagesResponse: {
            /**
             * Messages
             * @description Liste des messages de la page actuelle
             */
            messages: components["schemas"]["ReadMessage"][];
            /**
             * Has Next Page
             * @description Indique s'il y a une page suivante
             */
            has_next_page: boolean;
            /**
             * Next Cursor
             * @description Curseur pour la page suivante (base64 encodé). Null si pas de page suivante
             */
            next_cursor?: string | null;
            /**
             * Has Previous Page
             * @description Indique s'il y a une page précédente
             */
            has_previous_page: boolean;
            /**
             * Previous Cursor
             * @description Curseur pour la page précédente (base64 encodé). Null si pas de page précédente
             */
            previous_cursor?: string | null;
        };
        /**
         * ReadMember
         * @description Schéma pour la lecture d'un membre - expose les champs nécessaires au front.
         */
        ReadMember: {
            /**
             * Id
             * Format: uuid
             * @description ID unique du membre
             */
            id: string;
            /**
             * Wa Jid
             * @description ID WhatsApp unique du membre
             */
            wa_jid: string;
            /**
             * Wa Name
             * @description Nom WhatsApp du membre
             */
            wa_name: string | null;
            /**
             * Display Name
             * @description Nom d'affichage du membre
             */
            display_name: string | null;
            /**
             * Phone Number
             * @description Numéro de téléphone du membre
             */
            phone_number: string | null;
            /**
             * Avatar Url
             * @description URL de l'avatar du membre
             */
            avatar_url: string | null;
            /**
             * Is Active
             * @description Indique si le membre est actif
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Date de création du membre
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Date de dernière mise à jour du membre
             */
            updated_at: string;
        };
        /**
         * ReadMessage
         * @description Schéma pour la lecture d'un message - expose les champs nécessaires au front.
         */
        ReadMessage: {
            /**
             * Id
             * Format: uuid
             * @description ID unique du message
             */
            id: string;
            /**
             * Thread Id
             * Format: uuid
             * @description ID du thread auquel le message appartient
             */
            thread_id: string;
            /**
             * Content
             * @description Contenu du message
             */
            content: string;
            /**
             * Wa Message Id
             * @description ID du message WhatsApp
             */
            wa_message_id: string | null;
            /** @description Statut de synchronisation WhatsApp */
            wa_status: components["schemas"]["WAStatus"];
            /**
             * Wa Forwarded At
             * @description Date de transfert WhatsApp
             */
            wa_forwarded_at: string | null;
            /**
             * Is Hidden
             * @description Indique si le message est masqué
             */
            is_hidden: boolean;
            /**
             * Hidden Reason
             * @description Raison du masquage du message
             */
            hidden_reason: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Date de création du message
             */
            created_at: string;
            /**
             * Mentionned Members
             * @description Liste des membres mentionnés dans le message
             */
            mentionned_members?: components["schemas"]["ReadMember"][];
        };
        /**
         * ReadThread
         * @description Schéma pour la lecture d'un thread - expose les champs nécessaires au front.
         */
        ReadThread: {
            /**
             * Id
             * Format: uuid
             * @description ID unique du thread
             */
            id: string;
            /**
             * Name
             * @description Nom du thread
             */
            name: string;
            /**
             * Slug
             * @description Slug unique du thread
             */
            slug: string;
            /**
             * Description
             * @description Description du thread
             */
            description?: string | null;
            /**
             * Wa Group Jid
             * @description ID de groupe WhatsApp
             */
            wa_group_jid: string;
            /**
             * Wa Group Name
             * @description Nom du groupe WhatsApp
             */
            wa_group_name?: string | null;
            /**
             * Is Active
             * @description Indique si le thread est actif
             */
            is_active: boolean;
            /**
             * Is Currently Locked
             * @description Indique si le thread est actuellement bloqué pour les nouveaux messages
             * @default false
             */
            is_currently_locked: boolean;
            /**
             * Last Wa Sync At
             * @description Dernière synchronisation WhatsApp
             */
            last_wa_sync_at?: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Date de création du thread
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Date de dernière mise à jour du thread
             */
            updated_at: string;
            /**
             * Has Password
             * @description Indique si le thread est protégé par un mot de passe, donc si c'est True tu affiche une dialog pour rentrer le mot de passe, sinon tu peux directement se connecter au thread
             * @default false
             */
            has_password: boolean;
        };
        /**
         * ReadThreadWithUserConnectionInfo
         * @description Schéma pour la lecture d'un thread avec les infos de connexion de l'utilisateur.
         */
        ReadThreadWithUserConnectionInfo: {
            /**
             * Id
             * Format: uuid
             * @description ID unique du thread
             */
            id: string;
            /**
             * Name
             * @description Nom du thread
             */
            name: string;
            /**
             * Slug
             * @description Slug unique du thread
             */
            slug: string;
            /**
             * Description
             * @description Description du thread
             */
            description?: string | null;
            /**
             * Wa Group Jid
             * @description ID de groupe WhatsApp
             */
            wa_group_jid: string;
            /**
             * Wa Group Name
             * @description Nom du groupe WhatsApp
             */
            wa_group_name?: string | null;
            /**
             * Is Active
             * @description Indique si le thread est actif
             */
            is_active: boolean;
            /**
             * Is Currently Locked
             * @description Indique si le thread est actuellement bloqué pour les nouveaux messages
             * @default false
             */
            is_currently_locked: boolean;
            /**
             * Last Wa Sync At
             * @description Dernière synchronisation WhatsApp
             */
            last_wa_sync_at?: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Date de création du thread
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Date de dernière mise à jour du thread
             */
            updated_at: string;
            /**
             * Has Password
             * @description Indique si le thread est protégé par un mot de passe, donc si c'est True tu affiche une dialog pour rentrer le mot de passe, sinon tu peux directement se connecter au thread
             * @default false
             */
            has_password: boolean;
            /**
             * Is Connected
             * @description Indique si l'utilisateur est connecté à ce thread
             * @default false
             */
            is_connected: boolean;
        };
        /**
         * StringMessage
         * @description Schémas pydantic pour le retour d'un message de type String
         */
        StringMessage: {
            /**
             * Message
             * @description Le message de réponse relatif au résultat de l'opération, ce message là sera forcément pour un succès, si c'est echec ca sera dans le champ 'error'
             */
            message: string;
        };
        /**
         * ThreadAuthRequest
         * @description Schéma pour la requête d'authentification d'un thread.
         */
        ThreadAuthRequest: {
            /**
             * Password
             * @description Mot de passe du thread si le thread en a un
             */
            password?: string | null;
        };
        /**
         * ThreadInfos
         * @description Schéma enveloppe pour un thread unique.
         */
        ThreadInfos: {
            /** Champ pour véreifier si la reequete à réussi, True si la requete a reussi, False sinon */
            success: boolean;
            /** Champ pour véreifier le code de status HTTP de la réponse, 200 pour les succès, 400 pour les erreurs client, 500 pour les erreurs serveur, etc. */
            status_code: number;
            /**
             * Champ de résultat
             * @description Présent seulement si la requet à réussi
             */
            result?: components["schemas"]["ReadThread"] | null;
            /**
             * Champ des erreurs
             * @description Présent seulement si la requete à échouée ou si quelque chose s'est mal passé durant le traitement
             */
            error?: components["schemas"]["AppError"] | null;
        };
        /**
         * ThreadWithUserConnectionInfo
         * @description Schéma enveloppe pour un thread unique avec les infos de connexion de l'utilisateur.
         */
        ThreadWithUserConnectionInfo: {
            /** Champ pour véreifier si la reequete à réussi, True si la requete a reussi, False sinon */
            success: boolean;
            /** Champ pour véreifier le code de status HTTP de la réponse, 200 pour les succès, 400 pour les erreurs client, 500 pour les erreurs serveur, etc. */
            status_code: number;
            /**
             * Champ de résultat
             * @description Présent seulement si la requet à réussi
             */
            result?: components["schemas"]["ReadThreadWithUserConnectionInfo"] | null;
            /**
             * Champ des erreurs
             * @description Présent seulement si la requete à échouée ou si quelque chose s'est mal passé durant le traitement
             */
            error?: components["schemas"]["AppError"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WAStatus
         * @description Statut des messages WhatsApp.
         * @enum {string}
         */
        WAStatus: "pending" | "queued" | "sent" | "delivered" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    hello_v1_hello_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    get_all_threads_v1_threads__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListThreadsInfos"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    create_thread_v1_threads__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThread"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadInfos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    get_connected_thread_info_v1_threads_actual_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadWithUserConnectionInfo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorMessage"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorMessage"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    get_connected_thread_members_v1_threads_actual_members_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMembersInfos"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorMessage"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorMessage"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    get_thread_by_slug_v1_threads_slug__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Le slug du thread à récupérer */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadWithUserConnectionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    connect_to_a_thread_v1_threads__thread_id__auth_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID du thread auquel on ve se connecter */
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalStringResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    get_thread_by_id_v1_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID du thread à récupérer */
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadWithUserConnectionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    create_message_v1_messages__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageInfos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    get_thread_messages_v1_messages_thread__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMessagesInfos"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorMessage"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorMessage"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    get_thread_messages_paginated_v1_messages_thread_paginated__get: {
        parameters: {
            query?: {
                /** @description Nombre de messages par page (1-100, par défaut 20) */
                limit?: number;
                /** @description Curseur de pagination (base64). None pour la première page */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessagesInfos"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorMessage"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
    get_message_by_id_v1_messages__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID du message à récupérer */
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageInfos"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorMessage"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorSchema"];
                };
            };
        };
    };
}
