import type { CommonApiBaseResponse, GlobalStringResponse } from "@/types/api/baseApiSchemas.ts"
import type { components } from "./apiRawSchemas";
import { z } from "zod" // generated by openapi-typescript


const ThreadLoginPayloadZodSchema = z.object(
    {
        password: z.string({error: 'Le mot de passe doit etre une string valide'})
            .min(1, {error: 'Le mot de passe doit contenir au moins 1 caractère'})
            .max(100, {error: 'Le mot de passe ne doit pas depasser 100 caractères'})
    }
)

export type ThreadLoginPayload = z.infer<typeof ThreadLoginPayloadZodSchema>

export type ConnectToThreadResponse = CommonApiBaseResponse<GlobalStringResponse>

export type ReadThread = components["schemas"]["ReadThreadWithUserConnectionInfo"]
export type GetThreadResponse = CommonApiBaseResponse<
    components["schemas"]["ReadThreadWithUserConnectionInfo"]
>


export type GetAllThreadsResponse = CommonApiBaseResponse<components["schemas"]["ReadThreadWithUserConnectionInfo"][]>

export type GetThreadMembersResponse = CommonApiBaseResponse<components['schemas']["ReadMember"][]>

export type GetThreadMessagesResponse = CommonApiBaseResponse<
    components["schemas"]["PaginatedMessagesResponse"]
>