import type { CommonApiBaseResponse, GlobalStringResponse } from "@/types/api/baseApiSchemas.ts"
import type { components } from "./apiRawSchemas"; // generated by openapi-typescript

export type ConnectToThreadResponse = GlobalStringResponse

export type GetConnectedThreadResponse = CommonApiBaseResponse<components["schemas"]["ReadThreadWithUserConnectionInfo"]>

export type GetThreadResponse = GetConnectedThreadResponse

export type GetAllThreadsResponse = CommonApiBaseResponse<components["schemas"]["ReadThreadWithUserConnectionInfo"][]>

export type GetThreadMembersResponse = CommonApiBaseResponse<components['schemas']["ReadMember"][]>

export type GetThreadMessagesResponse = CommonApiBaseResponse<
    components["schemas"]["PaginatedMessagesResponse"]
>